#include "ModelPreviewDialog.h"
#include "RunSettingsDialog.h"
#include "MeshBoundsCache.h"

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QGroupBox>
#include <QComboBox>
#include <QLabel>
#include <QPushButton>
#include <QDialogButtonBox>
#include <QFileInfo>
#include <QProcess>
#include <QMessageBox>
#include <QStandardPaths>
#include <QDir>
#include <QTimer>

#include <nlohmann/json.hpp>
#include <fstream>

using json = nlohmann::json;

ModelPreviewDialog::ModelPreviewDialog(SceneDocument* doc,
                                       RunSettingsDialog* runSettings,
                                       int entityIndex,
                                       QWidget* parent)
    : QDialog(parent)
    , m_doc(doc)
    , m_runSettings(runSettings)
    , m_entityIndex(entityIndex)
{
    setWindowTitle("Model Preview");
    setMinimumWidth(380);

    auto* layout = new QVBoxLayout(this);

    // ---- Entity info ----
    QString name = m_doc->EntityName(entityIndex);
    QString filepath;
    const auto& e = m_doc->EntityAt(entityIndex);
    if (e.contains("meshSource"))
        filepath = QString::fromStdString(
            e["meshSource"].value("filepath", std::string()));

    layout->addWidget(new QLabel("<b>" + name + "</b>", this));
    if (!filepath.isEmpty())
        layout->addWidget(new QLabel(QFileInfo(filepath).fileName(), this));

    // ---- UV Mode ----
    auto* uvGroup  = new QGroupBox("UV Mode", this);
    auto* uvLayout = new QFormLayout(uvGroup);

    m_uvModeCombo = new QComboBox(this);
    m_uvModeCombo->addItems({ "Default", "Flip V", "Flip U", "Flip Both" });

    // Sync current value from entity
    int currentUvMode = 1; // FlipV default
    if (e.contains("meshSource"))
        currentUvMode = e["meshSource"].value("uvMode", 1);
    m_uvModeCombo->setCurrentIndex(currentUvMode);

    uvLayout->addRow("UV Mode", m_uvModeCombo);
    layout->addWidget(uvGroup);

    connect(m_uvModeCombo, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &ModelPreviewDialog::OnUVModeChanged);

    // ---- Preview info ----
    layout->addWidget(new QLabel(
        "Launches PowerEngine with a minimal scene:\n"
        "  • This model at origin\n"
        "  • Floor plane\n"
        "  • Directional sun light",
        this));

    // ---- Buttons ----
    auto* previewBtn = new QPushButton("▶ Launch Preview", this);
    connect(previewBtn, &QPushButton::clicked,
            this, &ModelPreviewDialog::OnPreviewClicked);
    layout->addWidget(previewBtn);

    auto* closeBtn = new QDialogButtonBox(QDialogButtonBox::Close, this);
    connect(closeBtn, &QDialogButtonBox::rejected, this, &QDialog::reject);
    layout->addWidget(closeBtn);
}

void ModelPreviewDialog::OnUVModeChanged(int index)
{
    // Write UV mode back to entity's meshSource immediately so the main
    // scene inherits the setting when saved, not just the preview.
    auto& e = m_doc->EntityAt(m_entityIndex);
    if (e.contains("meshSource"))
    {
        e["meshSource"]["uvMode"] = index;
        emit m_doc->EntityModified(m_entityIndex);
    }
}

void ModelPreviewDialog::OnPreviewClicked()
{
    QString exePath = m_runSettings->ActiveExePath();
    QFileInfo exeInfo(exePath);
    if (!exeInfo.exists())
    {
        QMessageBox::warning(this, "Preview",
                             "PowerEngine.exe not found:\n" + exePath +
                                 "\n\nCheck Run Settings.");
        return;
    }

    // Write the temp scene next to the exe so relative asset paths
    // (same as the full scene) resolve correctly inside the engine.
    QString tempScenePath = exeInfo.absolutePath() + "/_preview_scene.psef";
    GenerateTempScene(tempScenePath);

    // Write the engine_config.ini (same as normal Run)
    QString iniPath = exeInfo.absolutePath() + "/engine_config.ini";
    // Reuse MainWindow's WriteEngineConfig logic by writing inline here —
    // we can't call MainWindow directly, but the format is trivial.
    {
        QFile ini(iniPath);
        if (ini.open(QIODevice::WriteOnly | QIODevice::Text))
        {
            QTextStream out(&ini);
            out << "; Preview launch — auto-generated by ModelPreviewDialog\n";
            out << "width="     << m_runSettings->Width()        << "\n";
            out << "height="    << m_runSettings->Height()       << "\n";
            out << "vsync="     << (m_runSettings->VSync() ? 1 : 0) << "\n";
            out << "hz="        << m_runSettings->RefreshRateHz()  << "\n";
            out << "show_grid=" << (m_runSettings->ShowGrid() ? 1 : 0) << "\n";
        }
    }

    QProcess* proc = new QProcess(this);
    proc->setWorkingDirectory(exeInfo.absolutePath());
    proc->setProgram(exePath);
    proc->setArguments({ "--scene=" + tempScenePath });
    proc->startDetached();

    // Delete the temp file after a delay long enough for the engine to
    // have opened and parsed it. Deleting immediately raced against the
    // detached process's startup and could delete the file before it
    // was ever read, causing the engine to fall back to its built-in
    // demo scene (which looked like "the full scene" launching instead).
    QTimer::singleShot(5000, this, [tempScenePath]() {
        QFile::remove(tempScenePath);
    });
}

void ModelPreviewDialog::GenerateTempScene(const QString& outPath) const
{
    const auto& entity = m_doc->EntityAt(m_entityIndex);

    json root;
    root["version"]  = 1;
    json entities    = json::array();

    // ---- The model entity (copy transform + meshSource + material overrides) ----
    json modelEntity;
    modelEntity["id"]   = 0;
    modelEntity["name"] = m_doc->EntityName(m_entityIndex).toStdString();

    // Center it at origin for the preview, but lift it vertically so its
    // AABB minimum sits exactly on the floor (Y=0) instead of the model's
    // own pivot/origin — otherwise models whose pivot isn't at their base
    // clip halfway through the floor plane.
    double scaleY = 1.0;
    json scaleArr = entity.contains("transform")
                        ? entity["transform"].value("scale", json::array({1,1,1}))
                        : json::array({1.0, 1.0, 1.0});
    if (scaleArr.is_array() && scaleArr.size() >= 2)
        scaleY = scaleArr[1].get<double>();

    double liftY = 0.0;
    if (entity.contains("meshSource") &&
        entity["meshSource"].value("type", "") == "file")
    {
        QString filepath = QString::fromStdString(
            entity["meshSource"].value("filepath", std::string()));
        const auto& bounds = MeshBoundsCache::Get(filepath);
        if (bounds.Valid)
        {
            // bounds are in the mesh's own local space (already includes
            // node transforms baked in by MeshBoundsCache); scale by the
            // entity's Y scale to match how it will actually render.
            liftY = -static_cast<double>(bounds.Min.y()) * scaleY;
        }
    }

    modelEntity["transform"] = {
        { "position", { 0.0, liftY, 0.0 } },
        { "rotation", entity.contains("transform")
                         ? entity["transform"].value("rotation", json::array({0,0,0}))
                         : json::array({0.0, 0.0, 0.0}) },
        { "scale", scaleArr }
    };

    if (entity.contains("meshSource"))
        modelEntity["meshSource"] = entity["meshSource"];

    if (entity.contains("useAutoMaterial"))
        modelEntity["useAutoMaterial"] = entity["useAutoMaterial"];

    if (entity.contains("material"))
        modelEntity["material"] = entity["material"];

    if (entity.contains("materialOverride"))
        modelEntity["materialOverride"] = entity["materialOverride"];

    entities.push_back(modelEntity);

    // ---- Floor plane ----
    json floor;
    floor["id"]   = 1;
    floor["name"] = "Floor";
    floor["transform"] = {
        { "position", { 0.0, 0.0, 0.0 } },
        { "rotation", { 0.0, 0.0, 0.0 } },
        { "scale",    { 1.0, 1.0, 1.0 } }
    };
    floor["meshSource"] = {
        { "type",   "plane" },
        { "width",  30.0 },
        { "height", 30.0 }
    };
    floor["useAutoMaterial"] = false;
    floor["material"] = {
        { "albedo",    { 0.2, 0.2, 0.2 } },
        { "metallic",  0.0 },
        { "roughness", 0.9 },
        { "ambientOcc", 1.0 },
        { "albedoMap", "" }, { "normalMap", "" },
        { "specularMap", "" }, { "glossinessMap", "" }
    };
    entities.push_back(floor);

    // ---- Directional sun ----
    json sun;
    sun["id"]   = 2;
    sun["name"] = "Sun";
    sun["transform"] = {
        { "position", { 0.0, 0.0, 0.0 } },
        { "rotation", { 0.0, 0.0, 0.0 } },
        { "scale",    { 1.0, 1.0, 1.0 } }
    };
    sun["directionalLight"] = {
        { "direction", { 0.5, -1.0, 0.3 } },
        { "color",     { 1.0, 0.95, 0.9 } },
        { "intensity", 3.0 }
    };
    entities.push_back(sun);

    root["entities"] = entities;

    std::ofstream file(outPath.toStdString());
    if (file.is_open())
        file << root.dump(2);
}
